//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    
    public partial class LatestItems
    {
        public int ItemID { get; set; }
        public int ItemCategoryID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public bool IsActive { get; set; }
        public double ItemPrice { get; set; }
        public int UOMTypeID { get; set; }
        public int SupplierID { get; set; }
        public double MaxOrderLimit { get; set; }
        public string ImagePath { get; set; }
    }
}
