//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    
    public partial class OrderVerifyCode
    {
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CustomerID { get; set; }
        public int CurrentStatusID { get; set; }
        public double TotalOrderAmount { get; set; }
        public double CommisionPercentage { get; set; }
        public bool IsCustomerConfirmed { get; set; }
        public bool IsSupplierConfirmed { get; set; }
        public string VerificationCode { get; set; }
    }
}
