//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    
    public partial class OrdersCommission
    {
        public string OrderNo { get; set; }
        public double CommisionPercentage { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalOrderAmount { get; set; }
        public decimal SellerCost { get; set; }
        public decimal CompanyCommission { get; set; }
    }
}
