//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    
    public partial class ProductsCategories
    {
        public Nullable<int> ItemCategoryID { get; set; }
        public string ItemCategoryDesc { get; set; }
        public string SupplierRegion { get; set; }
    }
}
