//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int SupplierID { get; set; }
        public string FullName { get; set; }
        public string CompanyName { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierRegion { get; set; }
        public string SupplierCity { get; set; }
        public int LinkedLoginUserID { get; set; }
        public string ContactNumber { get; set; }
        public string SupplierEmail { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual LoginUser LoginUser { get; set; }
    }
}
