//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFoodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOMType
    {
        public UOMType()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int UOMTypeID { get; set; }
        public string UOMTypeDescription { get; set; }
        public bool IsDecimal { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
